### ISSUE TITLE
add MIME type recommendation

### ISSUE THREAD

**Issue by michaelficarra** [edn-format/edn#53] opened 2013-06-13 16:30 UTC
`application/edn` should probably be appropriate, no?

**Comment by igorw** [comment] 2013-06-13 18:11
Instead of just making something up, the type should be [registered with IANA](http://www.iana.org/assignments/media-types).

**Comment by puredanger** [comment] 2013-09-03 19:38
Duplicate of #43

**Closed as completed** 2014-01-07 22:32 UTC
