### ISSUE TITLE
Escaping of quotes and backslashes in strings

### ISSUE THREAD

**Issue by igorw** [edn-format/edn#46] opened 2013-03-14 22:51 UTC
Escaping of double quotes and backslashes in strings is not specified at all.

I would assume that:
- `"foo\\bar"` => `foo\bar`
- `"foo\"bar"` => `foo"bar`

And the clojure implementation confirms this. It should be specified in edn though.

**Comment by richhickey** [comment] 2014-01-07 15:20
Dupe of #49

**Closed as completed by richhickey** 2014-01-07 15:20 UTC
